# This is a config for E2B sandbox template.
# You can use template ID (va1xgyb5e2lbkfv6lbpk) or template name (DEVAI-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("DEVAI-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("DEVAI-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('DEVAI-nextjs-test-2')

team_id = "58928475-ba43-4587-8377-6c0ae16d0e7a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "DEVAI-nextjs-test-2"
template_id = "va1xgyb5e2lbkfv6lbpk"
